matrixorigin/matrixone-operator

- .github/actions/dev_env/action.yml
- pkg/controllers/components/pod_control.go
- pkg/controllers/components/pvc_control.go
- pkg/controllers/components/service_control.go
- pkg/controllers/components/statefulset_control.go
- pkg/controllers/matrixone/event.go
- pkg/controllers/matrixone/handler.go
- pkg/controllers/matrixone/interface.go
- pkg/controllers/utils/utils.go
N/A
This PR tries to simplify current codebase via the type parameter introduced in go 1.18. However, due to the limitations of current go implementation, there are some drawbacks:
Cons:
- I cannot find any type constraints between generic `Object` and `ObjectList` (e.g. `*v1.Pod` and `*v1.PodList`) since the `metav1.ListInterface` is not generic. Reflection is used as a workaround.
- `Reader` and  `Writer` interface are replaced with functions since [method does not support type parameter yet](https://go.googlesource.com/proposal/+/refs/heads/master/design/43651-type-parameters.md#no-parameterized-methods)
Pros (from the author's perspective):
- Though the callee code is a bit more …
> refactor: simplify code via generic

- examples/logset.yaml
- examples/mo-cluster.yaml
- pkg/controllers/cnset/resource.go
Make the cluster runnable before CN is ready, so that we can add other logics.
```
kg po
NAME       READY   STATUS    RESTARTS      AGE
mo-cn-0    1/1     Running   0             29m
mo-cn-1    1/1     Running   0             29m
mo-dn-0    1/1     Running   0             29m
mo-dn-1    1/1     Running   0             29m
mo-log-0   1/1     Running   1 (29m ago)   30m
mo-log-1   1/1     Running   1 (29m ago)   30m
mo-log-2   1/1     Running   2 (29m ago)   30m
```
Not Available
Not Available
Not Available
> fix: make cluster runnable

- api/Makefile
- api/core/v1alpha1/cnset_webhook.go
- api/core/v1alpha1/dnset_webhook.go
- api/core/v1alpha1/logset_webhook.go
- api/core/v1alpha1/matrixonecluster_webhook.go
- api/core/v1alpha1/webhook.go
- charts/matrixone-operator/templates/_helpers.tpl
- charts/matrixone-operator/templates/deployment.yaml
- charts/matrixone-operator/templates/webhook-service.yaml
- charts/matrixone-operator/templates/webhook.yaml
- cmd/operator/main.go
- deploy/webhook/kustomization.yaml
- deploy/webhook/kustomizeconfig.yaml
- deploy/webhook/manifests.yaml
Add webhook deployment and deploy it to the nightly k8s env
Test:
```
kubectl apply -f examples/logset.yaml
The LogSet "logset" is invalid:
* spec.initialConfig.haKeeperReplicas: Invalid value: 3: haKeeperReplicas must not larger then logservice replicas
* spec.initialConfig.logShardReplicas: Invalid value: 3: logShardReplicas must not larger then logservice replicas
```
Not Available
Not Available
Not Available
> feat: add webhook deployment

- api/core/v1alpha1/common_types.go
- charts/matrixone-operator/templates/crds/core.matrixorigin.io_cnsets.yaml
- charts/matrixone-operator/templates/crds/core.matrixorigin.io_dnsets.yaml
- charts/matrixone-operator/templates/crds/core.matrixorigin.io_logsets.yaml
- charts/matrixone-operator/templates/crds/core.matrixorigin.io_webuis.yaml
- deploy/crds/core.matrixorigin.io_cnsets.yaml
- deploy/crds/core.matrixorigin.io_dnsets.yaml
- deploy/crds/core.matrixorigin.io_logsets.yaml
- deploy/crds/core.matrixorigin.io_webuis.yaml
- hack/kind-e2e.sh
- pkg/controllers/common/common.go
- pkg/controllers/dnset/const.go
- pkg/controllers/logset/configmap.go
Fixes #
1. Fix one syntax error in the start script
2. Add `publishNotReadyAddresses: true` to make the DNS record available during startup
3. Optimize the nslookup command in case any errors occur
4. Depend on https://github.com/matrixorigin/matrixone/pull/5140 
Not Available
Not Available
> Fix the start script issue and add some minor improvements

- api/core/v1alpha1/logset_types.go
- api/core/v1alpha1/logset_webhook.go
- api/core/v1alpha1/matrixonecluster_types.go
- api/core/v1alpha1/matrixonecluster_webhook_test.go
- api/core/v1alpha1/zz_generated.deepcopy.go
- charts/matrixone-operator/templates/crds/core.matrixorigin.io_logsets.yaml
- charts/matrixone-operator/templates/crds/core.matrixorigin.io_matrixoneclusters.yaml
- deploy/crds/core.matrixorigin.io_logsets.yaml
- deploy/crds/core.matrixorigin.io_matrixoneclusters.yaml
- docs/reference/api-reference.md
- examples/mo-cluster.yaml
- hack/e2e.sh
- pkg/controllers/common/common.go
- pkg/controllers/logset/bootstrap.go
- pkg/controllers/logset/controller.go
- pkg/controllers/logset/controller_test.go
- pkg/controllers/logset/sts_test.go
- pkg/controllers/mocluster/controller.go
- pkg/controllers/mocluster/controller_test.go
- test/e2e/logset_test.go
- test/e2e/matrixonecluster_test.go
close #252 
close #248 
This PR contains several minor fixes / feats:
1. Write the initial credentials of MO to a k8s secret;
2. Fix `e2e.sh`, avoid corrupting a cluster that already has e2e or operator running;
3. Fix hanging logset Pods on logset deletion, i.e. GC failed logset Pod;
4. Refine `LogSet` config, remove the `HAKeeperReplicas` field;
Not Available
Not Available
Not Available
> feat: initialize mo credential can GC failed logset Pod

- pkg/controllers/cnset/resource.go
This PR advertise CN address to the cluster through `listen-address` configuration.
The configuration should be changed to `service-address` later, since `listen-address` should be managed separately with the address we want to expose to clients (a.k.a. `service-address`)
Not Available
Not Available
Not Available
> feat: expose CN address to clients

- api/core/v1alpha1/cnset_types.go
This PR fix a panic issue when DN dep is not set for CN while a logset dep is set.
Not Available
Not Available
Not Available
> fix: panic issue when dnset dep is not

- Makefile
- charts/matrixone-operator/values.yaml
- pkg/controllers/cnset/resource.go
- pkg/controllers/common/consts.go
- pkg/controllers/dnset/resource.go
- pkg/controllers/dnset/resource_test.go
close #304 
The configuration will be constructed as below:
CN:
```toml
[cn]
uuid = "00000000-0000-0000-0000-200000000000"
listen-address = "0.0.0.0:6002"
service-address = "test-tp-cn-0.test-tp-cn-headless.e2e-1679290889849056000.svc:6002"
sql-address = "test-tp-cn-0.test-tp-cn-headless.e2e-1679290889849056000.svc:6001"
role = "TP"
[cn.lockservice]
service-address = "test-tp-cn-0.test-tp-cn-headless.e2e-1679290889849056000.svc:6003"
listen-address = "0.0.0.0:6003"
```
DN:
```toml
[dn]
uuid = "00000000-0000-0000-0000-100000000000"
service-address = "test-dn-0.test-dn-headless.e2e-1679290889849056000.svc:41010"
listen-address = "0.0.0.0:41010"
[dn.lockservice]
service-address = …
```
> feat: setup lock-service communication in operator

- cmd/operator/main.go
- pkg/controllers/cnlabel/controller.go
- pkg/hacli/hakeeper_client.go
close #345
For better performance, operator now caches HAKeeper client, which should be evicted on cluster recreation. This PR add cache eviction and logservice readiness check to make the CN label controller robust.
Not Available
Not Available
> fix: fixed CN label sync on cluster recreation

- api/core/v1alpha1/matrixonecluster_webhook.go
- go.mod
- go.sum
- pkg/controllers/logset/controller.go
- pkg/controllers/logset/controller_test.go
Fixes #302 
Automatically failover majority logset Pods is risky, this PR introduce failover limit to ensure failover never migrate majority pods.
Not Available
Not Available
> fix: add failover limit

- pkg/controllers/cnset/controller.go
- pkg/controllers/cnstore/controller.go
Fixes CN scaling behavior
1. Failed/Completed Pod may abort failover (scale-out)
2. There is no CN to accept migrated sessions on Pod rolling-re-create scenario
Not Available
Not Available
Not Available
> fix: fixed pod management behavior on CN scaling

- api/core/v1alpha1/cnset_types.go
- charts/matrixone-operator/templates/crds/core.matrixorigin.io_cnsets.yaml
- deploy/crds/core.matrixorigin.io_cnsets.yaml
- pkg/controllers/cnset/controller.go
Fixes # https://github.com/matrixorigin/MO-Cloud/issues/1321
only when cn pod ready, the cluster `ready` condition should be true
There are two ways to fix this probelm:
1. the simple one, let `cn.status.replicas` mean the ready replicas, not the total replicas, that is what this pr does. also in `unit-agent`, field `cn.status.replicas` means the ready replicas.
2. the complex one, add another `cn.status.readyReplicas` field to indicate ready replicas
in openkruise cloneset the field `cs.Status.Replicas` means the total replicas
> fix: set cnset status replicas to cloneset ready replicas

- pkg/controllers/br/command.go
mo-backup new version need sha256 checksum, generate the checksum before restore
Not Available
Not Available
Not Available
> fix: gen sha256 sum before restore

- pkg/controllers/cnset/resource.go
- pkg/controllers/cnset/resource_test.go
close https://github.com/matrixorigin/MO-Cloud/issues/2044
```
mysql> show backend servers;
+--------------------------------------+---------------------+------------+-----------------------------------------------+
| UUID                                 | Address             | Work State | Labels                                        |
+--------------------------------------+---------------------+------------+-----------------------------------------------+
| 62343135-3136-3437-3661-353239383339 | 172.20.144.131:6001 | Working    | account:ba537a2b_43e7_4a2c_a6fe_b945278ef41a; |
| 65363231-3433-3463-3339-336564666237 | 172.20.150.3:6001   | Draining   |                                               |
| …
```
> fix: set CN draining if store-drain-enabled

- Makefile
- api/core/v1alpha1/cnclaim_helper.go
- api/core/v1alpha1/cnclaim_types.go
- pkg/controllers/cnclaim/controller.go
- pkg/controllers/cnclaim/controller_test.go
- pkg/controllers/cnclaimset/controller.go
- pkg/controllers/cnpool/controller.go
- pkg/controllers/cnpool/controller_test.go
- pkg/controllers/cnstore/pooling.go
This PR introduce two changes:
1. Draining Pod will be deleted if draining timed out, to avoid workload intervention;
2. pool controller will watch claims refers to the pool to achieve more responsive reconciliation
Not Available
Not Available
Not Available
> feat: delete draining timeout pod and watch claim on pool

- api/core/v1alpha1/store_helper.go
- pkg/controllers/cnstore/controller.go
- pkg/controllers/cnstore/pooling.go
- pkg/controllers/common/cnstore.go
issue: https://github.com/matrixorigin/MO-Cloud/issues/3007
Not Available
Not Available
Not Available
> fix: fixed connection anno

- api/core/v1alpha1/proxy_types.go
- api/core/v1alpha1/zz_generated.deepcopy.go
- charts/matrixone-operator/templates/crds/core.matrixorigin.io_matrixoneclusters.yaml
- charts/matrixone-operator/templates/crds/core.matrixorigin.io_proxysets.yaml
- deploy/crds/core.matrixorigin.io_matrixoneclusters.yaml
- deploy/crds/core.matrixorigin.io_proxysets.yaml
- docs/reference/api-reference.md
- pkg/controllers/cnset/resource.go
- pkg/controllers/proxyset/resource.go
Fixes #
CI测试大部分将会由cn+dn+log转为proxy+cn+dn+log，目前机房中通过在mo cluster的yaml里面指定cn service的annotation来指定lb的ip，转为proxy之后无法通过以上方式指定lb的ip，故在operator的proxy set中增加对ServiceAnnotations字段的支持
Not Available
Not Available
> feature: support `serviceAnnotations` for proxy set

- pkg/controllers/cnpool/controller.go
- pkg/controllers/cnpool/controller_test.go
ref: https://github.com/matrixorigin/MO-Cloud/issues/2928
Skip already deleted Pod when sync CN Pool, leave the deleted pod to terminating controller.
Not Available
Not Available
> fix: skip already deleted pod when sync CNPools

- pkg/controllers/cnset/controller.go
Fixes # mcloud #3317
support updated pvc when rolling update CNSet, pvc size and storageclass may change, when changing resource `profile` of CNSet
Not Available
Not Available
> fix: support update pvc when rolling update

- charts/matrixone-operator/Chart.yaml
- charts/matrixone-operator/values.yaml
Fixes : release operator for issue mocloud #3317
support update pvc when cloneset rolling update
Not Available
Not Available
Not Available
___
enhancement, configuration changes
___
- Updated the `version` field in `Chart.yaml` from `1.2.0-alpha.2` to `1.2.0-alpha.3`.
- Updated the image tag in `values.yaml` from `1.2.0-alpha.2` to `1.2.0-alpha.3`.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Configuration changes
<tr>
<td>
<details>
<summary><strong>Chart.yaml</strong><dd><code>Bump chart version to …
> release 1.2.0-alpha.3

- kind.yaml
- pkg/controllers/cnstore/pooling.go
part of: https://github.com/matrixorigin/MO-Cloud/issues/3221
Not Available
Not Available
Not Available
___
Bug fix, Configuration changes
___
- Removed hardcoded `recycleTimeout` and replaced it with `GetStoreDrainTimeout` from `ScalingConfig` in `poolingCNReconcile` function.
- Added usage of `GetMinDelayDuration` from `ScalingConfig` for delay duration check.
- Enabled `MemoryQoS` feature gate in `kind.yaml` configuration file.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Bug fix
<tr>
<td>
<details> …
> fix: cn-pool reclaim should respect storeDrainTimeout

- charts/matrixone-operator/templates/webhook.yaml
[[Bug]: Operator Webhooks are using common name](https://github.com/matrixorigin/matrixone-operator/issues/451)
Not Available
Not Available
Not Available
___
Bug fix
___
- Fixed a name collision issue in the AdmissionWebhook configurations.
- Renamed `mutating-webhook-configuration` to `matrixone-operator-mutating-webhook`.
- Renamed `validating-webhook-configuration` to `matrixone-operator-validating-webhook`.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Bug fix
<tr>
<td>
<details> …
> fix: AdmissionWebhook name collision

- charts/kruise/.helmignore
- charts/kruise/Chart.yaml
- charts/kruise/README.md
- charts/kruise/templates/_helpers.tpl
- charts/kruise/templates/apps.kruise.io_advancedcronjobs.yaml
- charts/kruise/templates/apps.kruise.io_broadcastjobs.yaml
- charts/kruise/templates/apps.kruise.io_clonesets.yaml
- charts/kruise/templates/apps.kruise.io_containerrecreaterequests.yaml
- charts/kruise/templates/apps.kruise.io_daemonsets.yaml
- charts/kruise/templates/apps.kruise.io_imagepulljobs.yaml
- charts/kruise/templates/apps.kruise.io_nodeimages.yaml
- charts/kruise/templates/apps.kruise.io_nodepodprobes.yaml
- charts/kruise/templates/apps.kruise.io_persistentpodstates.yaml
- charts/kruise/templates/apps.kruise.io_podprobemarkers.yaml
- charts/kruise/templates/apps.kruise.io_resourcedistribution.yaml
- charts/kruise/templates/apps.kruise.io_sidecarsets.yaml
- charts/kruise/templates/apps.kruise.io_statefulsets.yaml
- charts/kruise/templates/apps.kruise.io_uniteddeployments.yaml
- charts/kruise/templates/apps.kruise.io_workloadspreads.yaml
- charts/kruise/templates/manager.yaml
- charts/kruise/templates/policy.kruise.io_podunavailablebudgets.yaml
- charts/kruise/templates/rbac_role.yaml
- charts/kruise/templates/webhookconfiguration.yaml
- charts/kruise/values.yaml
- charts/matrixone-operator/values.yaml
- part of https://github.com/matrixorigin/MO-Cloud/issues/3911
- part of https://github.com/matrixorigin/MO-Cloud/issues/3859
Vendor kruise chart and make some change:
1. support disable kruise in mo-operator by settting `.kruise.enabled=false` in mo-operator values;
2. support disable webhookconfiguration in kruise by setting `.webhookConfiguration.enabled=false` in kruise values;
3. support use external provisioned SA for kruise-manager by setting `manager.serviceAccountName="foobar"` in kruise values, the ClusterRole and ClusterRoleBinding of kruise-manager will not be created in this case;
4. support use external provisioned SA for kruise-daemon by setting `daemon.serviceAccountName="foobar"` in kruise values, the …
> feat: vendor kruise chart

- charts/matrixone-operator/Chart.yaml
- charts/matrixone-operator/templates/deployment.yaml
- charts/matrixone-operator/templates/webhook.yaml
- charts/matrixone-operator/values.yaml
Fixes # https://github.com/matrixorigin/MO-Cloud/issues/3911
user can deploy webhook resoruce separately, for security reason
Not Available
Not Available
___
enhancement
___
- Added support to conditionally skip the creation of the webhook resource during Helm installation by introducing a new `webhook.createResource` flag.
- Updated the Helm chart version to 1.2.0-alpha.6.
- This enhancement allows users to deploy the webhook resource separately for security reasons.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Configuration …
> feat: support skip creating webhook resource when helm install

- charts/matrixone-operator/Chart.yaml
- charts/matrixone-operator/templates/deployment.yaml
- charts/matrixone-operator/values.yaml
Fixes # https://github.com/matrixorigin/MO-Cloud/issues/3911
user can define matrixone operator arguments in helm chart values.yaml
Not Available
Not Available
___
enhancement
___
- Added support for defining operator arguments in the Helm chart `values.yaml`, allowing users to customize operator behavior.
- Updated the Helm chart version to 1.2.0-alpha.8.
- Introduced a new `args` section in `values.yaml` to specify default operator arguments, including `-leader-elect`.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Configuration …
> feat: support define operator args in helm chart values

- .github/workflows/release_image.yml
- pkg/controllers/cnclaim/controller.go
- pkg/controllers/cnpool/controller.go
part of: https://github.com/matrixorigin/MO-Cloud/issues/2289
> fix: direct pod should be rollout

- api/core/v1alpha1/semver_test.go
- pkg/controllers/common/podset.go
- pkg/controllers/common/podset_test.go
- pkg/webhook/cnset_webhook.go
- pkg/webhook/cnset_webhook_test.go
- pkg/webhook/common.go
- pkg/webhook/dnset_webhook_test.go
- pkg/webhook/logset_webhook_test.go
- pkg/webhook/proxy_webhook_test.go
https://github.com/matrixorigin/MO-Cloud/issues/4004
Not Available
Not Available
Not Available
___
Bug fix, Tests
___
- Improved the handling of semantic version annotations in the `SyncPodMeta` function to ensure robustness.
- Enhanced the `ValidateUpdate` function in the webhook to check for semantic version compatibility, ensuring that updates do not introduce incompatible versions.
- Updated multiple test files to use semantic versioned image tags, ensuring consistency and correctness in tests.
- Improved validation logic for `PodSet` semantic versions to ensure a valid semantic …
> fix: validate semver setting in webhook

- api/core/v1alpha1/common_types.go
- charts/matrixone-operator/templates/crds/core.matrixorigin.io_cnpools.yaml
- charts/matrixone-operator/templates/crds/core.matrixorigin.io_cnsets.yaml
- charts/matrixone-operator/templates/crds/core.matrixorigin.io_dnsets.yaml
- charts/matrixone-operator/templates/crds/core.matrixorigin.io_logsets.yaml
- charts/matrixone-operator/templates/crds/core.matrixorigin.io_matrixoneclusters.yaml
- charts/matrixone-operator/templates/crds/core.matrixorigin.io_proxysets.yaml
- charts/matrixone-operator/templates/crds/core.matrixorigin.io_webuis.yaml
- deploy/crds/core.matrixorigin.io_cnpools.yaml
- deploy/crds/core.matrixorigin.io_cnsets.yaml
- deploy/crds/core.matrixorigin.io_dnsets.yaml
- deploy/crds/core.matrixorigin.io_logsets.yaml
- deploy/crds/core.matrixorigin.io_matrixoneclusters.yaml
- deploy/crds/core.matrixorigin.io_proxysets.yaml
- deploy/crds/core.matrixorigin.io_webuis.yaml
part of https://github.com/matrixorigin/MO-Cloud/issues/4219
Not Available
Not Available
Not Available
> fix: do not omit 0 replica

- pkg/controllers/mocluster/controller.go
Fixes # https://github.com/matrixorigin/MO-Cloud/issues/4074
some MatrixoneCluster CRs should skip sync for some reason, like debug or migrate MatrixoneCluster CR subresource  management to other controllers. if matrixonecluster cr has annotation `matrixorigin.io/skip-sync`, operator controller will skip sync cr
Not Available
Not Available
___
enhancement
___
- Introduced a new annotation `matrixorigin.io/skip-sync` to allow skipping the synchronization of MatrixOneCluster custom resources.
- Updated the `Observe` and `Finalize` methods in the `MatrixOneClusterActor` to check for the …
> feat: support skip syncing matrixonecluster cr

- api/core/v1alpha1/operator_version.go
- pkg/controllers/cnset/controller.go
- pkg/webhook/cnset_webhook.go
- pkg/webhook/common.go
- pkg/webhook/dnset_webhook.go
- pkg/webhook/logset_webhook.go
- pkg/webhook/proxy_webhook.go
- test/e2e/logset_test.go
https://github.com/matrixorigin/MO-Cloud/issues/4406
> fix: fixed defaults and validations for operator version

- pkg/controllers/cnclaim/controller.go
> fix: fixed migration for direct-pod

- pkg/controllers/cnclaim/migrate.go
- pkg/controllers/cnpool/controller.go
https://github.com/matrixorigin/MO-Cloud/issues/3952
Not Available
Not Available
Not Available
> fix: fixed cnpool scaling when inplace update is enabled 

- examples/mo-cluster.yaml
- go.mod
- go.sum
- pkg/controllers/cnset/controller.go
- pkg/controllers/common/volume.go
- pkg/controllers/dnset/controller.go
- pkg/controllers/logset/controller.go
- pkg/webhook/cnset_webhook.go
- pkg/webhook/common.go
- pkg/webhook/dnset_webhook.go
- pkg/webhook/logset_webhook.go
- test/e2e/claim_test.go
https://github.com/matrixorigin/matrixone/issues/9335
> feat: support volume expansion

- pkg/controllers/common/configmap.go
> fix: add roll-out log to track config change history
