docker-compose/Dockerfile
docker-compose/Makefile
docker-compose/docker-compose.yml

Fixes #17 
The image is stored in the same location as the official image
Not Available
Not Available

config docker store path

---

docker-compose/Makefile
docker-compose/README.md

Fixes #16 
Printing Cluster Information
Not Available
Not Available

print cluster info

---

Makefile
README.md
docs/cluster.md
docs/design.md
docs/getting_started.md
docs/tools.md

Fixes #32 
Not Available
Not Available
Not Available

Optimize the document

---

Makefile

Fixes #36 
Not Available
Not Available
Not Available

fix deploy command

---

docs/getting_started.md

Fixes #49
Not Available
Not Available
Not Available

Update doc about helm deployment

---

.github/mergify.yml
.github/workflows/workflows.yml

Fixes #
Not Available
Not Available
Not Available

optimize workflow

---

.github/mergify.yml

Fixes #
Not Available
Not Available
Not Available

[CI]Fix label on reviewed mergify config

---

.github/actions/cluster/action.yml
.github/actions/e2e_kind/action.yml
.github/actions/helm_check/action.yml
examples/tiny-cluster.yaml
third_part/mo-docker/system_vars_config.toml

Fixes #
Not Available
Not Available
Not Available

[FEATURE]Update default cluster config

---

Makefile
README.md
docs/api.md
docs/architecture.md
docs/cluster.md
docs/dev_guide.md
docs/getting_started.md
docs/tencentcloud/tencent.md

Not Available
- Fix broken links
- Use permalink for code referencing
- Fix some typos
It would be better to cover these style issues in linters, which is left for future exploration.
Not Available

docs(*): refine doc styles and typos

---

.github/mergify.yml

Fixes #
1. remove default reviewer 
2. change put to queue option (required reviewer change 1 to 2)
Not Available
Not Available

update merfigy 

---

pkg/controllers/matrixone/predicates.go

As titled.
Not Available
Not Available
Not Available

chore: fix typo and test mergify

---

docs/rfc/2022-07-04-logset.md

This RFC propose a new resource `LogSet` to manage the lifecycle of a log service cluster on Kubernetes.

docs: propose logset RFC

---

docs/rfc/2022-07-05-mo-cluster.md

This RFC describes an overview of how will the operator work and be used.
Make sure you view this PR in preview mode to check the rendered graph https://github.com/matrixorigin/matrixone-operator/blob/0246d0d2bf496f0c79745e78aa4542caa26187d7/docs/rfc/2022-07-05-mo-cluster.md

docs: add mo-operator RFC

---

docs/rfc/2022-07-05-mo-cluster.md

Fixes some typos found in doc.

style: fix rfc typos

---

.github/mergify.yml

chore: enfore all review comments are resolved before merging

---

.github/workflows/test_workflows.yml
.github/workflows/update_workflows.yml

Since we are going to start `v0.1` iteration, lots of code will be changed/added incrementally, disable CI before we reach a stable point.

chore: disable ci checks during v0.1 iteration

---

docs/rfc/2022-07-04-logset.md

Refine RFC according to preview discussion.

docs: refine logset bootstrap

---

.github/mergify.yml

Fixes #
Not Available
Not Available
Not Available

ci(mergify): update mergify for short term

---

runtime/pkg/reconciler/reconciler.go

Fixes #
Update klog label, So we can use it in other packages
Not Available
Not Available

perf: udpate reconcile klog level label

---

api/core/v1alpha1/common_helpers.go
api/core/v1alpha1/toml_config.go
api/core/v1alpha1/toml_config_test.go
examples/logset.yaml
pkg/controllers/common/common.go
pkg/controllers/logset/bootstrap.go
pkg/controllers/logset/configmap.go
pkg/controllers/logset/controller.go
pkg/controllers/logset/discovery.go
pkg/controllers/logset/sts.go
runtime/pkg/reconciler/reconciler.go

part of #174 
Tested in AWS EKS with gp2 EBS volume 
```
kg po
NAME       READY   STATUS    RESTARTS        AGE
logset-0   1/1     Running   0               4m5s
logset-1   1/1     Running   0               4m5s
logset-2   1/1     Running   2 (3m52s ago)   4m5s
```
Bootstrap logservice and make it work
Not Available
Not Available

feat: bootstrap logset

---

api/core/v1alpha1/cnset_types.go
api/core/v1alpha1/common_types.go
api/core/v1alpha1/dnset_types.go
api/core/v1alpha1/logset_types.go
charts/matrixone-operator/templates/crds/core.matrixorigin.io_cnsets.yaml
charts/matrixone-operator/templates/crds/core.matrixorigin.io_dnsets.yaml
charts/matrixone-operator/templates/crds/core.matrixorigin.io_logsets.yaml
charts/matrixone-operator/templates/crds/core.matrixorigin.io_matrixoneclusters.yaml
deploy/crds/core.matrixorigin.io_cnsets.yaml
deploy/crds/core.matrixorigin.io_dnsets.yaml
deploy/crds/core.matrixorigin.io_logsets.yaml
deploy/crds/core.matrixorigin.io_matrixoneclusters.yaml

Makes the `kubectl get` result more human friendly:
```
kg logset
NAME     IMAGE                    REPLICAS   AGE
logset   aylei/mo-service:0.1.2   3          19h
```
Not Available
Not Available
Not Available

feat: add printed columns for CRD

---

api/core/v1alpha1/logset_helpers.go
api/core/v1alpha1/logset_types.go
charts/matrixone-operator/templates/crds/core.matrixorigin.io_logsets.yaml
charts/matrixone-operator/templates/crds/core.matrixorigin.io_matrixoneclusters.yaml
cmd/operator/main.go
deploy/crds/core.matrixorigin.io_logsets.yaml
deploy/crds/core.matrixorigin.io_matrixoneclusters.yaml
pkg/controllers/common/common.go
pkg/controllers/logset/controller.go
pkg/controllers/logset/store.go
pkg/controllers/logset/sts.go
runtime/pkg/reconciler/actor.go
runtime/pkg/reconciler/event.go
runtime/pkg/reconciler/reconciler.go
runtime/pkg/util/util.go

close #151 
1. Make reconcile more efficient with increased reconcile interval 
2. Add failover logic
3. Requeue logset when there is any change to the underlying statefulset, so that failover can be responsive
Not Available
Not Available

feat: add failover for logset

---

api/core/v1alpha1/logset_helpers.go
pkg/controllers/mocluster/controller.go
runtime/pkg/reconciler/reconciler.go

part of https://github.com/matrixorigin/matrixone-operator/issues/assigned/aylei
Not Available
Not Available
Not Available

feat: cnset and dnset depend on logset

---

pkg/controllers/logset/store.go

Fixes #
fix build error
k8s.io/apimachinery/pkg/apis/meta/v1.Time
composite literal uses unkeyed fields
env: go1.19 amd64
Not Available

fix: build error

---

charts/matrixone-operator/templates/crds/core.matrixorigin.io_cnsets.yaml
charts/matrixone-operator/templates/crds/core.matrixorigin.io_dnsets.yaml
charts/matrixone-operator/templates/crds/core.matrixorigin.io_logsets.yaml
charts/matrixone-operator/templates/crds/core.matrixorigin.io_matrixoneclusters.yaml
cmd/operator/main.go
deploy/crds/core.matrixorigin.io_cnsets.yaml
deploy/crds/core.matrixorigin.io_dnsets.yaml
deploy/crds/core.matrixorigin.io_logsets.yaml
deploy/crds/core.matrixorigin.io_matrixoneclusters.yaml
pkg/controllers/cnset/const.go
pkg/controllers/cnset/controller.go
pkg/controllers/cnset/resource.go
pkg/controllers/common/common.go
pkg/controllers/dnset/controller.go
pkg/controllers/dnset/resource.go
pkg/controllers/logset/store.go

Signed-off-by: wanglei <wanglei4687@gmail.com>
Fixes #
Not Available
Not Available
Not Available

feat: add strategy of cn and dn

---

pkg/controllers/cnset/resource.go
pkg/controllers/dnset/controller.go
pkg/controllers/dnset/resource.go

Fixes #
Not Available
Not Available
Not Available

fix: name typo

---

.gitignore
Makefile

Fixes #
Not Available
Not Available
Not Available

chore: optimize helm charts build

---

api/core/v1alpha1/logset_webhook.go
charts/matrixone-operator/templates/role.yaml
cmd/operator/main.go
examples/mo-cluster.yaml
pkg/controllers/cnset/controller.go
pkg/controllers/cnset/resource.go
pkg/controllers/common/common.go
pkg/controllers/dnset/controller.go
pkg/controllers/dnset/resource.go
pkg/controllers/logset/controller.go
pkg/controllers/logset/sts.go
pkg/controllers/mocluster/controller.go
runtime/pkg/reconciler/errors.go
runtime/pkg/reconciler/reconciler.go
runtime/pkg/util/util.go

close #152 
Not Available
Not Available
Not Available

[feat] support s3 static credential access for cn/dn

---

examples/mo-cluster.yaml
pkg/controllers/common/common.go
pkg/controllers/dnset/resource.go
pkg/controllers/logset/bootstrap.go
pkg/controllers/logset/configmap.go

Latest mo version changed the configuration layout, this PR adapt with it.
Not Available
Not Available
Not Available

fix: adapt operator to latest mo version

---

api/Makefile
api/core/v1alpha1/cnset_webhook.go
api/core/v1alpha1/common_types.go
api/core/v1alpha1/dnset_webhook.go
api/core/v1alpha1/logset_webhook.go
api/core/v1alpha1/matrixonecluster_webhook.go
api/core/v1alpha1/matrixonecluster_webhook_test.go
api/core/v1alpha1/toml_config_test.go
api/core/v1alpha1/webhook.go
api/core/v1alpha1/webhook_suite_test.go
api/go.mod
api/go.sum
charts/matrixone-operator/templates/crds/core.matrixorigin.io_cnsets.yaml
charts/matrixone-operator/templates/crds/core.matrixorigin.io_dnsets.yaml
charts/matrixone-operator/templates/crds/core.matrixorigin.io_logsets.yaml
charts/matrixone-operator/templates/crds/core.matrixorigin.io_matrixoneclusters.yaml
deploy/crds/core.matrixorigin.io_cnsets.yaml
deploy/crds/core.matrixorigin.io_dnsets.yaml
deploy/crds/core.matrixorigin.io_logsets.yaml
deploy/crds/core.matrixorigin.io_matrixoneclusters.yaml
examples/mo-cluster.yaml
pkg/controllers/logset/configmap.go

1. Add webhook implementation for MatrixOneCluster CR
2. Add some end to end test cases for webhook
Not Available
Not Available
Not Available

feat: add matrixonecluster webhook

---

examples/logset.yaml
examples/mo-cluster.yaml

Use official multi-arch image to avoid using node selector
Not Available
Not Available
Not Available

use official multi-arch image

---

.github/workflows/update_workflows.yml
test/e2e/matrixonecluster_test.go

Fix the update workflow (docker push)
Not Available
Not Available
Not Available

fix docker push

---

Makefile
api/core/v1alpha1/webui_types.go
charts/matrixone-operator/templates/crds/core.matrixorigin.io_matrixoneclusters.yaml
charts/matrixone-operator/templates/crds/core.matrixorigin.io_webuis.yaml
cmd/operator/main.go
deploy/crds/core.matrixorigin.io_matrixoneclusters.yaml
deploy/crds/core.matrixorigin.io_webuis.yaml
examples/mo-cluster.yaml
pkg/controllers/mocluster/controller.go
pkg/controllers/webui/resource.go

Fixes #
Not Available
deploy:
`kubectl apply -f example/mo-cluster.yaml`
proxy:
` kubectl port-forward svc/mo-webui 6190:80 `
Not Available

fix: webui runable

---

test/e2e/matrixonecluster_test.go

As titled. Part of #212 
Not Available
Not Available
Not Available

test: add matrixonecluster rolling-update test

---

pkg/controllers/cnset/controller.go
pkg/controllers/cnset/controller_test.go

part of #210 
Not Available
Not Available
Not Available

feat: add cn basic ut

---

Makefile
pkg/controllers/common/reason_types.go
pkg/controllers/dnset/controller.go
pkg/controllers/logset/controller.go

Fixes #
Not Available
Not Available
Not Available

refactor: add reason types

---

api/go.mod
api/go.sum
go.mod
go.sum
pkg/controllers/common/common.go
pkg/controllers/logset/bootstrap.go
pkg/controllers/logset/configmap.go
pkg/controllers/logset/configmap_test.go
pkg/controllers/logset/controller.go
pkg/controllers/logset/sts.go
pkg/controllers/logset/sts_test.go
test/e2e/logset_test.go

close https://github.com/matrixorigin/matrixone-operator/issues/238
Not Available
Not Available
Not Available

fix: scale-out and failover should not cause rolling-update

---

pkg/controllers/webui/const.go
pkg/controllers/webui/controller.go
pkg/controllers/webui/controller_test.go
pkg/controllers/webui/utils.go

Fixes #
Not Available
Not Available
Not Available

feat: add basic webui ut

---

go.mod
go.sum
hack/kind-e2e.sh
test/e2e/matrixonecluster_test.go
test/e2e/sql/sql.go
test/e2e/suite_test.go
test/e2e/util/portforward.go

part of #212 
Not Available
Not Available
Not Available

test: add end to end sql test in e2e

---

api/core/v1alpha1/cnset_webhook_test.go
api/core/v1alpha1/dnset_webhook_test.go
api/core/v1alpha1/logset_webhook_test.go
api/core/v1alpha1/matrixonecluster_webhook_test.go

close #244 
For backward compatibility, we should have test cases to ensure the webhook always accept objects that are valid in old versions.
Not Available
Not Available

test: add webhook compatiability test

---

Dockerfile
Makefile
hack/kind-e2e.sh
hack/lib.sh

Improve local e2e experience. 
1. Rename `PROXY` to `GOPRXOY`, so it properly inherit the `GOPROXY` env from user's environment;
2. Install `kubectl`, `helm` and `kind` automatically if they are not installed, to improve the user experience
Not Available
Not Available

test: improve local e2e dev experience

---

charts/matrixone-operator/values.yaml
pkg/controllers/mocluster/controller.go
pkg/controllers/mocluster/controller_test.go

Fix the credential ref namespace.
Not Available
Not Available
Not Available

fix: credential ref should be in same namespace

---

docs/getting_started.md

Update according to #253 
Not Available
Not Available
Not Available

docs: update document about credentials

---

cmd/operator/main.go
runtime/pkg/metrics/collector.go

part of #143 , this PR add more metrics of mo-operator, especially conditional metrics.
Not Available
Not Available
Not Available

feat: add more condition metrics for resources

---

api/core/v1alpha1/matrixonecluster_types.go
charts/matrixone-operator/templates/crds/core.matrixorigin.io_matrixoneclusters.yaml
deploy/crds/core.matrixorigin.io_matrixoneclusters.yaml
pkg/controllers/mocluster/controller.go

Part of #242, this field will be used to tell the user whether the cluster is ready for sql connection.
Not Available
Not Available
Not Available

feat: add phase to cluster status

---

Makefile
pkg/controllers/cnset/resource.go
pkg/controllers/cnset/utils.go
test/e2e/matrixonecluster_test.go

This PR expose CN `service-address` and `sql-address` to other components in the cluster.
Not Available
Not Available
Not Available

add service address to cn

---

charts/matrixone-operator/values.yaml

Update the default image tag to avoid confusion.
Not Available
Not Available
Not Available

Update default image tag

---

.github/workflows/release.yml
README.md

Signed-off-by: wanglei <wanglei4687@gmail.com>
Fixes #229 
Not Available
Not Available

feat: add release action

---

pkg/controllers/common/fileservice.go
pkg/controllers/dnset/resource_test.go

All data should be written to the volume/cacheVolume
Not Available
Not Available
Not Available

fix: data-dir should be set to persistent volume

---

pkg/controllers/logset/sts.go
pkg/controllers/logset/sts_test.go
pkg/controllers/mocluster/controller.go
pkg/controllers/mocluster/controller_test.go

Fixes pvc retention policy not synced.
Not Available
Not Available
Not Available

fix: sync pvc retention policy from mo to logservice

---

api/core/v1alpha1/logset_types.go
api/core/v1alpha1/logset_webhook.go
api/core/v1alpha1/zz_generated.deepcopy.go
charts/matrixone-operator/templates/crds/core.matrixorigin.io_logsets.yaml
charts/matrixone-operator/templates/crds/core.matrixorigin.io_matrixoneclusters.yaml
cmd/operator/main.go
deploy/crds/core.matrixorigin.io_logsets.yaml
deploy/crds/core.matrixorigin.io_matrixoneclusters.yaml
docs/reference/api-reference.md
examples/mo-full.yaml
pkg/controllers/logset/controller.go

Fixes #294 
Also, this PR add an full example of MO cluster.
In some env, we need to disable failover since there is no additional resources.
Not Available
Not Available

feat: able to disable failover and refine failover strategy

---

Makefile
api/core/v1alpha1/cnset_types.go
api/core/v1alpha1/dnset_types.go
charts/matrixone-operator/templates/role.yaml
charts/matrixone-operator/values.yaml
cmd/operator/main.go
go.mod
pkg/controllers/dnset/controller.go
pkg/controllers/dnset/resource.go
pkg/controllers/mocluster/controller.go
pkg/controllers/mocluster/controller_test.go
pkg/utils/utils.go

close #296 
This can minimize the unavailable time during update.
Not Available
Not Available

fix: fixed rolling-update order between components

---

api/core/v1alpha1/cnset_types.go
api/core/v1alpha1/cnset_webhook.go
api/core/v1alpha1/zz_generated.deepcopy.go
charts/matrixone-operator/templates/crds/core.matrixorigin.io_cnsets.yaml
charts/matrixone-operator/templates/crds/core.matrixorigin.io_matrixoneclusters.yaml
deploy/crds/core.matrixorigin.io_cnsets.yaml
deploy/crds/core.matrixorigin.io_matrixoneclusters.yaml
docs/reference/api-reference.md
pkg/controllers/cnset/controller.go
pkg/controllers/cnset/resource.go
pkg/controllers/cnset/utils.go
pkg/utils/utils.go
test/e2e/cnset_test.go

close #260 
In OP scenario, we may need to specify the CN nodeport to get consistent behavior between installations.
Not Available
Not Available

support set nodeport for cn

---

pkg/controllers/common/fileservice.go
pkg/controllers/common/fileservice_test.go
pkg/controllers/common/template.go

This PR separate the cache dir of ETL and S3 fs.
Not Available
Not Available
Not Available

feat: separate cache dir for better management

---

charts/matrixone-operator/values.yaml

Release 0.7.0-alpha.2
Not Available
Not Available
Not Available

chore: release 0.7.0-alpha.2

---

.github/workflows/release.yml
charts/matrixone-operator/Chart.yaml

Currently the chart release will run on every time main updated, which is not desired.
Not Available
Not Available
Not Available

fix: helm version and chart publish workflow

---

.github/actions/checks/action.yml
.github/actions/dev_env/action.yml
.github/env
.golangci.yml
Dockerfile
api/core/v1alpha1/common_helpers.go
api/core/v1alpha1/logset_webhook.go
api/features/features.go
api/go.mod
charts/matrixone-operator/templates/configmap.yaml
charts/matrixone-operator/values.yaml
cmd/operator/main.go
go.mod
go.sum
pkg/controllers/cnset/controller.go
pkg/controllers/common/operatorcfg.go
pkg/controllers/dnset/controller.go
pkg/controllers/logset/bucketclaim.go

Fixes #325
Not Available
Not Available
Not Available

feat: add feature gate and set s3 reclaim to alpha

---

api/features/features.go
charts/matrixone-operator/values.yaml
cmd/operator/main.go

Add a feature-gate for proxy set support
Not Available
Not Available
Not Available

Add feature gate for proxy set support

---

charts/matrixone-operator/Chart.yaml
charts/matrixone-operator/values.yaml
examples/mo-full.yaml

Bump chart to 0.8.0-alpha.1, update doc
Not Available
Not Available
Not Available

bump operator chart to 0.8.0-alpha.1

---

api/core/v1alpha1/cnset_types.go
api/core/v1alpha1/cnset_webhook.go
api/core/v1alpha1/common_types.go
api/core/v1alpha1/dnset_types.go
api/core/v1alpha1/zz_generated.deepcopy.go
pkg/controllers/cnset/resource.go
pkg/controllers/common/podset.go
pkg/controllers/dnset/resource.go
pkg/controllers/mocluster/controller.go

Enable DNS identity by default so that the UUID collision can be avoided in mulit-CNSet scenario
Not Available
Not Available
Not Available

enable dns identity by default

---

api/core/v1alpha1/cnset_webhook.go
api/core/v1alpha1/cnset_webhook_test.go

This PR improve CN label validation to avoid confusing config passed.
Not Available
Not Available
Not Available

feat: enhance CN label validation

---

charts/matrixone-operator/Chart.yaml
charts/matrixone-operator/values.yaml
pkg/controllers/proxyset/resource.go

Part of #350 
Not Available
Not Available
Not Available

feat: add readiness probe for proxy

---

examples/mo-full.yaml

Fixes #
Not Available
Not Available
Not Available

fix: fix full yaml example

---

pkg/controllers/common/fileservice.go
pkg/controllers/common/fileservice_test.go

Workaround https://github.com/matrixorigin/matrixone/issues/9507
Not Available
Not Available
Not Available

fix: workaround sizeBytes unit suffix

---

charts/matrixone-operator/Chart.yaml
charts/matrixone-operator/values.yaml
pkg/controllers/logset/controller.go

Bump chart version
Not Available
Not Available
Not Available

bump chart to 0.8.0-alpha.4

---

pkg/controllers/bucketclaim/jobtpl.go

Fixes #356
Not Available
Not Available
Not Available

fix: remove bucket pod labels inherit from logset

---

api/core/v1alpha1/bucketclaim_helpers.go
pkg/controllers/bucketclaim/controller.go
pkg/controllers/cnset/controller.go
pkg/controllers/dnset/controller.go
pkg/controllers/logset/bucketclaim.go
pkg/controllers/logset/controller.go
test/e2e/bucket_test.go

Fixes #334
Not Available
Not Available
Not Available

fix: skip startup bucket job if no running instance for mo cluster

---

api/core/v1alpha1/matrixonecluster_webhook.go
api/core/v1alpha1/matrixonecluster_webhook_test.go

fix defaulting webhook for matrxonecluster CR
Not Available
Not Available
Not Available

fix: fixed CNGroups defaults in matrixonecluster CR

---

pkg/controllers/bucketclaim/jobtpl.go

Fixes #367
Not Available
Not Available
Not Available

fix: make bucket deletion pod as best effort

---

charts/matrixone-operator/Chart.yaml
charts/matrixone-operator/values.yaml
pkg/controllers/cnset/controller.go
pkg/controllers/mocluster/controller.go

Close #375 
Not Available
Not Available
Not Available

fix pub prevernt cluster reconciling

---

api/core/v1alpha1/cnset_types.go
api/core/v1alpha1/cnset_webhook_test.go
api/core/v1alpha1/common_types.go
api/core/v1alpha1/dnset_webhook_test.go
api/core/v1alpha1/webhook.go
charts/matrixone-operator/templates/crds/core.matrixorigin.io_cnsets.yaml
charts/matrixone-operator/templates/crds/core.matrixorigin.io_dnsets.yaml
charts/matrixone-operator/templates/crds/core.matrixorigin.io_logsets.yaml
charts/matrixone-operator/templates/crds/core.matrixorigin.io_matrixoneclusters.yaml
deploy/crds/core.matrixorigin.io_cnsets.yaml
deploy/crds/core.matrixorigin.io_dnsets.yaml
deploy/crds/core.matrixorigin.io_logsets.yaml
deploy/crds/core.matrixorigin.io_matrixoneclusters.yaml
docs/reference/api-reference.md
examples/mo-cluster.yaml
pkg/controllers/cnset/resource.go
pkg/controllers/common/fileservice.go
pkg/controllers/common/fileservice_test.go
pkg/controllers/common/template.go
pkg/controllers/dnset/resource.go
pkg/controllers/dnset/resource_test.go
pkg/controllers/logset/configmap.go
pkg/controllers/proxyset/resource.go

close #378 
Not Available
Not Available
Not Available

feat: refine cache config

---

api/core/v1alpha1/cnset_types.go
api/core/v1alpha1/common_helpers.go
api/core/v1alpha1/common_helpers_test.go
charts/matrixone-operator/templates/crds/core.matrixorigin.io_cnsets.yaml
charts/matrixone-operator/templates/crds/core.matrixorigin.io_matrixoneclusters.yaml
deploy/crds/core.matrixorigin.io_cnsets.yaml
deploy/crds/core.matrixorigin.io_matrixoneclusters.yaml
pkg/controllers/cnlabel/controller.go
pkg/controllers/cnset/controller.go
pkg/controllers/cnset/resource.go
pkg/controllers/common/consts.go

Fixes #380 
1. This PR fix CN label sync for legacy cluster;
2. This PR add CNSet `/scale` API support
Not Available
Not Available

feat: support scale API and fix cn labels

---

api/core/v1alpha1/common_helpers.go
api/core/v1alpha1/proxy_webhook.go
charts/matrixone-operator/values.yaml
deploy/webhook/manifests.yaml

close #284 
Not Available
Not Available
Not Available

feat: enable proxy pprof by default

---

Makefile
pkg/controllers/cnstore/controller.go

close #400 
Not Available
Not Available
Not Available

support cn cordon

---

pkg/controllers/cnstore/controller.go
pkg/controllers/mocluster/controller.go

close #405 
This PR remove the `PatchCNStore` RPC call (which cause old versions of logservice panic) if `StoreDrain` is disabled for CNSets.
We also need to document that `StoreDrain` can only be enabled for MO version > 0.8
Not Available
Not Available

fix: fixed MO 0.8 compatibility

---

pkg/controllers/cnstore/controller.go

Patch CN pod readiness when CN is cordoned to avoid traffic routed from k8s service.
Not Available
Not Available
Not Available

fix: fixed pod readiness on cordon

---

pkg/controllers/cnset/controller.go

close https://github.com/matrixorigin/matrixone/issues/11620
Currently, in-place rolling-update will hang if max-unavailable is 0 since the readiness-gate is not properly set as ready after rolling-update complete
Not Available
Not Available

fix: fixed in-place update

---

api/core/v1alpha1/matrixonecluster_helpers.go
api/core/v1alpha1/matrixonecluster_types.go
api/core/v1alpha1/matrixonecluster_webhook.go
api/core/v1alpha1/matrixonecluster_webhook_test.go
api/core/v1alpha1/zz_generated.deepcopy.go
charts/matrixone-operator/templates/crds/core.matrixorigin.io_matrixoneclusters.yaml
deploy/crds/core.matrixorigin.io_matrixoneclusters.yaml
docs/reference/api-reference.md
examples/mo-cluster.yaml
examples/mo-full.yaml
examples/mo-on-s3.yaml
pkg/controllers/mocluster/controller.go
pkg/controllers/mocluster/controller_test.go
test/e2e/matrixonecluster_test.go
test/e2e/util/template.go

close #414 
Not Available
Not Available
Not Available

chore: rename dn to tn

---

charts/matrixone-operator/Chart.yaml
charts/matrixone-operator/values.yaml

Not Available
Not Available
Not Available

release 1.0.0-alpha.1

---

api/core/v1alpha1/dnset_webhook.go
api/core/v1alpha1/dnset_webhook_test.go
pkg/controllers/dnset/resource.go
test/e2e/matrixonecluster_test.go

close #427 
Not Available
Not Available
Not Available

fix: accept [tn] config

---

Makefile
pkg/controllers/cnstore/controller.go

close #431 
Not Available
Not Available
Not Available

fix: fixed cn-store draining timeout behavior

---

go.mod
pkg/controllers/cnstore/controller.go
pkg/controllers/cnstore/metric.go
pkg/metric/types.go

This PR expose the CN connection account through Pod Annotation and sync the deletion cost to optimize the scaling order
Not Available
Not Available
Not Available

feat: expose connection account and deletion cost

---

charts/matrixone-operator/Chart.yaml
charts/matrixone-operator/values.yaml

Release matrixone-operator 1.0.0-alpha.2
Not Available
Not Available
Not Available

chore: bump chart 1.0.0-alpha.2

---

pkg/controllers/cnset/resource.go
test/e2e/matrixonecluster_test.go

Fix a panic issue when CN prom is enabled
Not Available
Not Available
Not Available

fix: fix panic when enable cn prom

---

pkg/controllers/common/consts.go
pkg/controllers/dnset/controller.go
pkg/controllers/logset/controller.go

This PR fix MO default metrics port
Not Available
Not Available
Not Available

fix: fixed default status port

---

pkg/controllers/common/template.go

**Which issue(s) this PR fixes:** 
Fixes # https://github.com/matrixorigin/MO-Cloud/issues/1211
Not Available
Not Available
Not Available

fix: set in-place update grace period seconds to 10

---

pkg/controllers/cnstore/controller.go

Fixes #
Not Available
Not Available
Not Available

fix: fixed logging panic

---

pkg/controllers/cnset/controller.go

Disable CN PVC reuse.
Not Available
Not Available
Not Available

disable pvc reuse

---

pkg/controllers/cnstore/controller.go
pkg/controllers/dnset/controller.go
pkg/controllers/logset/controller.go

fix metrics exporting of log and DN
Not Available
Not Available
Not Available

fix: fixed metrics exporting of log and DN

---

pkg/controllers/dnset/controller.go
pkg/controllers/logset/controller.go

Fixes #
Not Available
Not Available
Not Available

fix:fixed dn and log enable prometheus-s

---

api/core/v1alpha1/cnset_webhook.go
api/core/v1alpha1/common_helpers.go
api/core/v1alpha1/common_types.go
api/core/v1alpha1/dnset_webhook.go
api/core/v1alpha1/logset_webhook.go
examples/minio.yaml
examples/mo-cluster-udf.yaml
examples/mo-full.yaml
hack/lib.sh
playground/minio.yaml

close #447 
Not Available
Not Available
Not Available

feat: automatically set recommended GODEBUG env

---

charts/matrixone-operator/Chart.yaml
charts/matrixone-operator/values.yaml

Fixes #
Not Available
Not Available
Not Available

chore: bump 1.0-rc1

---

pkg/controllers/common/fileservice.go

Fixes #
Not Available
Not Available
Not Available

fix: fixed s3 certificate config

---

charts/matrixone-operator/Chart.yaml
charts/matrixone-operator/values.yaml

release operator 1.0.0-rc4
Not Available
Not Available
Not Available

release: 1.0.0-rc4

---

pkg/hacli/hakeeper_client.go

Fixes #
Not Available
Not Available
Not Available

fix closing CN cache

---

pkg/controllers/cnclaim/controller.go
pkg/controllers/cnstore/pooling.go
pkg/hacli/hakeeper_client.go

sync more cn claim status
Not Available
Not Available
Not Available

feat: more cn claim status

---

api/core/v1alpha1/cnclaim_types.go
charts/matrixone-operator/templates/crds/core.matrixorigin.io_cnclaimsets.yaml
deploy/crds/core.matrixorigin.io_cnclaimsets.yaml
pkg/controllers/cnclaim/controller.go
pkg/controllers/cnclaimset/controller.go
pkg/controllers/cnpool/controller.go
pkg/controllers/cnstore/controller.go
pkg/controllers/cnstore/pooling.go
pkg/controllers/common/cnstore.go

Fixes #
Not Available
Not Available
Not Available

feat: fix scaling selector and draining timeout

---

api/core/v1alpha1/cnclaim_types.go
pkg/controllers/cnclaim/controller.go
pkg/controllers/cnclaim/controller_test.go
pkg/controllers/cnclaimset/controller.go

This feature change the owner label to be more generic
Not Available
Not Available
Not Available

feat: more generic owner label key

---

api/core/v1alpha1/cnclaim_types.go
pkg/controllers/cnclaim/controller.go
pkg/controllers/cnclaimset/controller.go

Fixes #
Not Available
Not Available
Not Available

fix: fixed claimset owner labelselector

---

api/core/v1alpha1/cnclaim_types.go
pkg/controllers/cnstore/controller.go
pkg/controllers/cnstore/pooling.go

ref: https://github.com/matrixorigin/MO-Cloud/issues/2383
Not Available
Not Available
Not Available

fix creation timeout and refine reclaim behavior

---

pkg/controllers/cnclaimset/controller.go
pkg/controllers/cnclaimset/controller_test.go
pkg/controllers/cnpool/controller.go
pkg/controllers/cnpool/controller_test.go

Fixes #
Not Available
Not Available
Not Available

fix: fixed deletion order, reclaim newer pod first

---

pkg/controllers/cnclaimset/controller.go
pkg/controllers/cnclaimset/controller_test.go

Fixes #
Not Available
Not Available
Not Available

more log about scale-in

---

pkg/controllers/cnstore/controller.go

ref: https://github.com/matrixorigin/MO-Cloud/issues/2426
Not Available
Not Available
Not Available

fix: fixed rolling-update stuck

---

charts/matrixone/.helmignore
charts/matrixone/Chart.yaml
charts/matrixone/templates/NOTES.txt
charts/matrixone/templates/_helpers.tpl
charts/matrixone/templates/mo-cluster.yaml
charts/matrixone/values.yaml

ref https://github.com/matrixorigin/MO-Cloud/issues/2466
Not Available
Not Available
Not Available

add new chart

---

pkg/controllers/proxyset/resource.go

https://github.com/matrixorigin/MO-Cloud/issues/2094
Not Available
Not Available
Not Available

feat: support collect proxy metrics

---

pkg/controllers/cnstore/controller.go

Fixes https://github.com/matrixorigin/MO-Cloud/issues/2416
Not Available
Not Available
Not Available

fix: fixed deletion-cost when scale-in cn pool

---

charts/matrixone/templates/_helpers.tpl
charts/matrixone/templates/deployment.yaml
charts/matrixone/templates/mo-cluster.yaml
charts/matrixone/values.yaml

…ults
- issue: https://github.com/matrixorigin/MO-Cloud/issues/2510
- issue: https://github.com/matrixorigin/MO-Cloud/issues/2511
support launch debugger when deploy mo and refine chart defa
Not Available
Not Available

feature: support launch debugger when deploy mo and refine chart defaults

---

api/core/v1alpha1/cnset_types.go
api/core/v1alpha1/zz_generated.deepcopy.go
charts/matrixone-operator/templates/crds/core.matrixorigin.io_cnpools.yaml
charts/matrixone-operator/templates/crds/core.matrixorigin.io_cnsets.yaml
charts/matrixone-operator/templates/crds/core.matrixorigin.io_matrixoneclusters.yaml
deploy/crds/core.matrixorigin.io_cnpools.yaml
deploy/crds/core.matrixorigin.io_cnsets.yaml
deploy/crds/core.matrixorigin.io_matrixoneclusters.yaml
docs/reference/api-reference.md
pkg/controllers/cnset/controller.go
pkg/controllers/cnstore/controller.go
pkg/controllers/common/cnstore.go
test/e2e/cnset_test.go

issue: https://github.com/matrixorigin/MO-Cloud/issues/2855
Not Available
Not Available
Not Available

able to terminate a CNSet gracefully

---

api/core/v1alpha1/proxy_webhook_test.go
api/core/v1alpha1/webhook.go
charts/matrixone-operator/templates/webhook.yaml
test/e2e/proxy_test.go

https://github.com/matrixorigin/MO-Cloud/issues/3054
Not Available
Not Available
Not Available

fix: fix proxy webhook

---

api/core/v1alpha1/semver.go
api/core/v1alpha1/semver_test.go

https://github.com/matrixorigin/MO-Cloud/issues/3226
Not Available
Not Available
Not Available

fix: fixed feature version judgement for LockMigration

---

go.mod
go.sum
pkg/controllers/cnclaim/controller.go
pkg/controllers/common/cnstore.go

issue: https://github.com/matrixorigin/MO-Cloud/issues/3240

fix: fixed panic when return nil error

---

api/core/v1alpha1/cnclaim_types.go
pkg/controllers/cnclaim/controller.go
pkg/controllers/cnclaim/controller_test.go
pkg/controllers/cnpool/controller.go
pkg/controllers/common/selector.go

fix: fixed claim outdated CN and owner label refine

---

api/core/v1alpha1/cnset_types.go
api/core/v1alpha1/dnset_types.go
api/core/v1alpha1/proxy_types.go
api/go.mod
api/go.sum
go.mod
go.sum
pkg/controllers/cnset/controller.go
pkg/controllers/dnset/controller.go
pkg/controllers/logset/controller.go
pkg/controllers/mocluster/controller.go
test/e2e/matrixonecluster_test.go

https://github.com/matrixorigin/MO-Cloud/issues/3059
Not Available
Not Available
Not Available

fix: fixed sync condition check

---

api/core/v1alpha1/common_helpers.go
api/core/v1alpha1/common_types.go
api/core/v1alpha1/zz_generated.deepcopy.go
charts/matrixone-operator/templates/crds/core.matrixorigin.io_cnpools.yaml
charts/matrixone-operator/templates/crds/core.matrixorigin.io_cnsets.yaml
charts/matrixone-operator/templates/crds/core.matrixorigin.io_dnsets.yaml
charts/matrixone-operator/templates/crds/core.matrixorigin.io_logsets.yaml
charts/matrixone-operator/templates/crds/core.matrixorigin.io_matrixoneclusters.yaml
charts/matrixone-operator/templates/crds/core.matrixorigin.io_proxysets.yaml
charts/matrixone-operator/templates/crds/core.matrixorigin.io_webuis.yaml
deploy/crds/core.matrixorigin.io_cnpools.yaml
deploy/crds/core.matrixorigin.io_cnsets.yaml
deploy/crds/core.matrixorigin.io_dnsets.yaml
deploy/crds/core.matrixorigin.io_logsets.yaml
deploy/crds/core.matrixorigin.io_matrixoneclusters.yaml
deploy/crds/core.matrixorigin.io_proxysets.yaml
deploy/crds/core.matrixorigin.io_webuis.yaml
docs/reference/api-reference.md
pkg/controllers/cnset/resource.go
pkg/controllers/common/cnstore.go
pkg/controllers/common/podset.go
pkg/controllers/dnset/controller.go
pkg/controllers/dnset/resource.go
pkg/controllers/logset/controller.go
pkg/controllers/logset/sts.go
pkg/controllers/proxyset/resource.go

This feature will help address https://github.com/matrixorigin/MO-Cloud/issues/3106
Not Available
Not Available
Not Available

feat: support pod based prometheus discovery

---

api/core/v1alpha1/proxy_types.go
charts/matrixone-operator/templates/crds/core.matrixorigin.io_matrixoneclusters.yaml
charts/matrixone-operator/templates/crds/core.matrixorigin.io_proxysets.yaml
deploy/crds/core.matrixorigin.io_matrixoneclusters.yaml
deploy/crds/core.matrixorigin.io_proxysets.yaml
docs/reference/api-reference.md
pkg/controllers/proxyset/resource.go

part of: https://github.com/matrixorigin/MO-Cloud/issues/3319
Not Available
Not Available
Not Available

feat: support set proxyset minReadySeconds

---

pkg/controllers/cnclaim/controller.go

[Fixes #](https://github.com/matrixorigin/MO-Cloud/issues/3177)
Not Available
Not Available
Not Available
___
Bug fix
___
- Added a check to skip errors when CN is not found in the `Finalize` method.
- Modified error handling in the `patchStore` method to avoid wrapping errors unnecessarily.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Bug fix
<tr>
<td>
<details>
<summary><strong>controller.go</strong><dd><code>Improve error handling for CN not found scenarios</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …

fix: skip CN not found

---

.github/workflows/release_image.yml

#510 
Not Available
Not Available
Not Available
___
Enhancement, Configuration changes
___
- Added a `workflow_dispatch` event trigger to the GitHub Actions workflow.
- Enhanced the workflow to push Docker images to the Aliyun Container Registry.
- Included a login step for the Alicloud Container Registry using secrets for authentication.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement
<tr>
<td>
<details>
<summary><strong>release_image.yml</strong><dd><code>Add support for pushing Docker images …

feat: push image to Aliyun Container Registry

---

cmd/operator/main.go
pkg/controllers/cnclaim/controller.go
pkg/controllers/common/pod.go
pkg/controllers/common/pod_test.go
pkg/mocli/cn_cache.go

https://github.com/matrixorigin/MO-Cloud/issues/3498
Not Available
Not Available
Not Available

fix: fixed cn label not synced after expiration

---

pkg/controllers/cnstore/controller.go
pkg/controllers/common/cnstore.go

https://github.com/matrixorigin/MO-Cloud/issues/3617
Not Available
Not Available
Not Available

feat: clear stats when CN restart

---

pkg/controllers/cnstore/controller.go

ref: https://github.com/matrixorigin/MO-Cloud/issues/3617

fix: fixed draining case when store not found in hakeeper

---

.github/workflows/release_image.yml

Fixes #
Not Available
Not Available
Not Available

chore: update public image repo

---

api/core/v1alpha1/bucketclaim_helpers.go
pkg/controllers/cnset/controller.go
pkg/controllers/dnset/controller.go
pkg/controllers/logset/bucketclaim.go
pkg/utils/utils.go
test/e2e/matrixonecluster_test.go

Fixes 
https://github.com/matrixorigin/MO-Cloud/issues/2951
Not Available
Not Available
Not Available

fix: bucket finalizer with hash suffix

---

cmd/rpccli/main.go
pkg/controllers/cnstore/controller.go
test/e2e/matrixonecluster_test.go

https://github.com/matrixorigin/MO-Cloud/issues/3741
Not Available
Not Available
Not Available

fix: migrate connections before migrate locks

---

pkg/controllers/br/backup_controller.go

https://github.com/matrixorigin/MO-Cloud/issues/3442
Not Available
Not Available
Not Available

delete job when complete backup

---

charts/matrixone-operator/templates/configmap.yaml
charts/matrixone-operator/values.yaml
cmd/operator/main.go
pkg/controllers/bucketclaim/controller.go
pkg/controllers/bucketclaim/jobtpl.go
pkg/controllers/bucketclaim/options.go
pkg/controllers/common/operatorcfg.go

Fixes #
Not Available
Not Available
Not Available

feature: enable custom bucket clean job

---

charts/matrixone-operator/Chart.yaml
charts/matrixone-operator/values.yaml

Fixes #
Not Available
Not Available
Not Available

chore: bump chart version

---

cmd/operator/main.go

Fixes #533 
Not Available
Not Available
Not Available

fix: support customize privilege

---

pkg/controllers/cnclaim/controller.go

https://github.com/matrixorigin/MO-Cloud/issues/3905
Not Available
Not Available
Not Available

fix panic when labels are nil of CNClaim

---

charts/matrixone-operator/Chart.yaml

part of https://github.com/matrixorigin/MO-Cloud/issues/3911
Test:
```
helm template charts/matrixone-operator --set kruise.enabled=false
```
Check the result, kruise resources are not included.
Not Available
Not Available
Not Available

use own kruise and fix skip kruise

---

.github/workflows/release_image.yml
api/core/v1alpha1/cnpool_types.go
pkg/controllers/cnclaim/controller.go
pkg/controllers/cnstore/controller.go
test/e2e/claim_test.go

follow up https://github.com/matrixorigin/MO-Cloud/issues/2118
Not Available
Not Available
Not Available

feat: support externally created direct pod

---

pkg/controllers/cnclaim/controller.go

part of https://github.com/matrixorigin/MO-Cloud/issues/2289
Not Available
Not Available
Not Available

fix: fixed cn claim pending

---

pkg/controllers/cnclaim/controller.go
pkg/controllers/cnclaim/migrate.go
pkg/controllers/cnstore/controller.go

https://github.com/matrixorigin/MO-Cloud/issues/3931

feat: more logs for store draining

---

go.mod
go.sum

___
dependencies
___
- Updated the `github.com/matrixorigin/controller-runtime` dependency to a new version in `go.mod`.
- Reflected the updated `controller-runtime` versions in `go.sum`.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Dependencies</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>go.mod</strong><dd><code>Update controller-runtime dependency version in go.mod</code>&nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
go.mod
<li>Updated the version of <code>github.com/matrixorigin/controller-runtime</code>.<br>
</details>
</td>
<td><a href="https://github.com/matrixorigin/matrixone-operator/pull/550/files#diff-33ef32bf6c23acb95f5902d7097b7a1d5128ca061167ec0716715b0b9eeaa5f6"> …

fix: fixed Patch behavior

---

pkg/webhook/logset_webhook.go
pkg/webhook/logset_webhook_test.go

ref: https://github.com/matrixorigin/MO-Cloud/issues/2634
Not Available
Not Available
Not Available

feat: support logset scale to 0

---

api/core/v1alpha1/cnpool_types.go
api/core/v1alpha1/operator_version.go
pkg/controllers/cnclaim/controller.go
pkg/controllers/cnpool/controller.go
pkg/controllers/cnset/controller.go
pkg/controllers/common/podset.go

issue: https://github.com/matrixorigin/MO-Cloud/issues/3952

feat: pool in-place rolling-update support

---

pkg/controllers/cnset/resource.go
pkg/controllers/dnset/resource.go
pkg/controllers/logset/configmap.go

https://github.com/matrixorigin/MO-Cloud/issues/4575
Not Available
Not Available
Not Available

fix: fixed accidentally rolling-update

---

pkg/controllers/cnpool/controller.go

https://github.com/matrixorigin/MO-Cloud/issues/4610

fix: fixed pool scaling failed

---

api/core/v1alpha1/semver.go
api/core/v1alpha1/semver_test.go

fix version check

---

pkg/controllers/logset/controller.go
pkg/controllers/logset/sts.go

fix: fixed logset bootstrap
